version: "3.8"

services:
  postgres:
    image: postgres:16
    container_name: postgres16
    environment:
      POSTGRES_USER: tansive
      POSTGRES_PASSWORD: abc@123
      POSTGRES_DB: hatchcatalog
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    restart: unless-stopped

volumes:
  pgdata:
