// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.6
// 	protoc        v5.29.3
// source: internal/tangent/session/proto/skill.proto

package proto

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	structpb "google.golang.org/protobuf/types/known/structpb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type SkillInvocation struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionId     string                 `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	InvocationId  string                 `protobuf:"bytes,2,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	SkillName     string                 `protobuf:"bytes,3,opt,name=skill_name,json=skillName,proto3" json:"skill_name,omitempty"`
	Args          *structpb.Struct       `protobuf:"bytes,4,opt,name=args,proto3" json:"args,omitempty"` // arbitrary map<string, any>
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillInvocation) Reset() {
	*x = SkillInvocation{}
	mi := &file_internal_tangent_session_proto_skill_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillInvocation) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillInvocation) ProtoMessage() {}

func (x *SkillInvocation) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tangent_session_proto_skill_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillInvocation.ProtoReflect.Descriptor instead.
func (*SkillInvocation) Descriptor() ([]byte, []int) {
	return file_internal_tangent_session_proto_skill_proto_rawDescGZIP(), []int{0}
}

func (x *SkillInvocation) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SkillInvocation) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *SkillInvocation) GetSkillName() string {
	if x != nil {
		return x.SkillName
	}
	return ""
}

func (x *SkillInvocation) GetArgs() *structpb.Struct {
	if x != nil {
		return x.Args
	}
	return nil
}

type SkillResult struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	InvocationId  string                 `protobuf:"bytes,1,opt,name=invocation_id,json=invocationId,proto3" json:"invocation_id,omitempty"`
	Output        *structpb.Struct       `protobuf:"bytes,2,opt,name=output,proto3" json:"output,omitempty"` // arbitrary map<string, any>
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SkillResult) Reset() {
	*x = SkillResult{}
	mi := &file_internal_tangent_session_proto_skill_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SkillResult) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SkillResult) ProtoMessage() {}

func (x *SkillResult) ProtoReflect() protoreflect.Message {
	mi := &file_internal_tangent_session_proto_skill_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SkillResult.ProtoReflect.Descriptor instead.
func (*SkillResult) Descriptor() ([]byte, []int) {
	return file_internal_tangent_session_proto_skill_proto_rawDescGZIP(), []int{1}
}

func (x *SkillResult) GetInvocationId() string {
	if x != nil {
		return x.InvocationId
	}
	return ""
}

func (x *SkillResult) GetOutput() *structpb.Struct {
	if x != nil {
		return x.Output
	}
	return nil
}

var File_internal_tangent_session_proto_skill_proto protoreflect.FileDescriptor

const file_internal_tangent_session_proto_skill_proto_rawDesc = "" +
	"\n" +
	"*internal/tangent/session/proto/skill.proto\x12\atansive\x1a\x1cgoogle/protobuf/struct.proto\"\xa1\x01\n" +
	"\x0fSkillInvocation\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12#\n" +
	"\rinvocation_id\x18\x02 \x01(\tR\finvocationId\x12\x1d\n" +
	"\n" +
	"skill_name\x18\x03 \x01(\tR\tskillName\x12+\n" +
	"\x04args\x18\x04 \x01(\v2\x17.google.protobuf.StructR\x04args\"c\n" +
	"\vSkillResult\x12#\n" +
	"\rinvocation_id\x18\x01 \x01(\tR\finvocationId\x12/\n" +
	"\x06output\x18\x02 \x01(\v2\x17.google.protobuf.StructR\x06output2M\n" +
	"\fSkillService\x12=\n" +
	"\vInvokeSkill\x12\x18.tansive.SkillInvocation\x1a\x14.tansive.SkillResultB Z\x1etansive_grpc_unary/proto;protob\x06proto3"

var (
	file_internal_tangent_session_proto_skill_proto_rawDescOnce sync.Once
	file_internal_tangent_session_proto_skill_proto_rawDescData []byte
)

func file_internal_tangent_session_proto_skill_proto_rawDescGZIP() []byte {
	file_internal_tangent_session_proto_skill_proto_rawDescOnce.Do(func() {
		file_internal_tangent_session_proto_skill_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_internal_tangent_session_proto_skill_proto_rawDesc), len(file_internal_tangent_session_proto_skill_proto_rawDesc)))
	})
	return file_internal_tangent_session_proto_skill_proto_rawDescData
}

var file_internal_tangent_session_proto_skill_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_internal_tangent_session_proto_skill_proto_goTypes = []any{
	(*SkillInvocation)(nil), // 0: tansive.SkillInvocation
	(*SkillResult)(nil),     // 1: tansive.SkillResult
	(*structpb.Struct)(nil), // 2: google.protobuf.Struct
}
var file_internal_tangent_session_proto_skill_proto_depIdxs = []int32{
	2, // 0: tansive.SkillInvocation.args:type_name -> google.protobuf.Struct
	2, // 1: tansive.SkillResult.output:type_name -> google.protobuf.Struct
	0, // 2: tansive.SkillService.InvokeSkill:input_type -> tansive.SkillInvocation
	1, // 3: tansive.SkillService.InvokeSkill:output_type -> tansive.SkillResult
	3, // [3:4] is the sub-list for method output_type
	2, // [2:3] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_internal_tangent_session_proto_skill_proto_init() }
func file_internal_tangent_session_proto_skill_proto_init() {
	if File_internal_tangent_session_proto_skill_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_internal_tangent_session_proto_skill_proto_rawDesc), len(file_internal_tangent_session_proto_skill_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_internal_tangent_session_proto_skill_proto_goTypes,
		DependencyIndexes: file_internal_tangent_session_proto_skill_proto_depIdxs,
		MessageInfos:      file_internal_tangent_session_proto_skill_proto_msgTypes,
	}.Build()
	File_internal_tangent_session_proto_skill_proto = out.File
	file_internal_tangent_session_proto_skill_proto_goTypes = nil
	file_internal_tangent_session_proto_skill_proto_depIdxs = nil
}
